language: ruby
rvm:
  - ruby-head
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1.10
  - 2.0.0-p648
script: bundle exec rspec --format documentation
cache: bundler
branches:
  only:
    - main
addons:
  code_climate:
    repo_token: eb44970f9efc497fb68c6ec1ce051dea530776b6a5bbe75e57734625f761ac86
env:
  global:
    - TOGGL_EMAIL=togglv8-limitusus@mailinator.com
    - TOGGL_USERNAME=Togglv8-Limitusus
    - TOGGL_USER_ID=6992251
    - OTHER_EMAIL=togglv8-limitusus2@mailinator.com
    - OTHER_USERNAME=Togglv8-Limitusus2
    - OTHER_USER_ID=6992583
    # COVERALLS_TOKEN
    - secure: "MhosgycXyzr3MXY3lnQiPFENrT6KzkK7fPF6ePPCEMv2dt/2Dv99Qf34xjlur4hSQSN2zA47itC7/Arn5tmSAhrTYqWR63y85/meeyNlyxtv9SmKTY5ScJh6FPYg+QS8Hkli5k+pSInOGxiShr0farl2hXKlA6ZJk4v3XHclXaJ4ctbCNg4UbLys8knkACfzoqCCZ6QuR03wq0mc7kMb45dNessHubKbIpvhtUxaWMgijiHgyfPyd8cYuIs9djDyGVfNqdZL4X0WOS91bsogPNveOzDA3dFcA8fNj3hBi0MvWfugHKVQjWaMZExE/B0xiX0gG7xc6GtJU8uYD/m78UrRL+i04EkgErYd1STwmYXe791OuMO8LYxvan7HkiuK4r8cWgZ+kvE+4aw5aCThGq0D1Vxx8hgaX8Kj7RGdaCDGZZJLM3+uyQdIG4BypNYTspwyfOLgtRMoO7bNwuAzgiAStiSDsJMSOaz4sRsXTRG7ipEW2EvoSFsVs2QHkb1oaULx/7F0IcWQbh3mEyg96+hIraMS9LAnQBdUbzVS1N1Hi7aE1CcBdeukabVasurqemh4xzbOdd3LhyEyqJojv+JjHULSBuF23qPrD1B97pRlktS38eI0YwhORkhtHsqRskNInqjyY7SPLqCZRwi6uW7NCey3ENm4kxfZs3MZBLI="
    # TOGGL_API_TOKEN
    - secure: "EMxm5v0oDHz8B0PJtubbxhwBBQQmVMuzHijz6J1Uln+VeOksPgkvEqT6SajX+PuFwqXk+EaNobgDlikb6gq9zkLmUQEJG6EuzdcTzqek4SjAgzr42ywSGhUdvlfN0cxBiBFqKaGY4q/64+F1BH9jamC7SSO+C+QpP+OGF9jWIPHIHZN2a+6cs9uFk4fs+fEjvorc50Rn6vvptlAXHapdws4ROzcFcITLeT16ka08wr4NaETs24I/o/kdG9fdGr7f+exVio4DDqJwFj8pj36xImaqEBIpmATBbBiT+uSdkEuOt/rJkbRNjpVeYABmwUiE1cmxHlxVTgI3PtfjBNlHy9e/F3DTBYG9+07HkgWu5fkMm2/tsMgVeRJQ2rh/xFxdj5eFMHj7Sl+hpSBCOU9o0x6pmB2cxjky03z15h/0LJfEckX4Lb9HnHPqgmBnAmpb7kmceU6jcUO1WB/hxKV9Be978IqSh7e2HCjJkeR7NUvFja1Yah1TVPjLAi7DQu9qhr3PwBOiZb4a+Yaig2LZkqvCjiiXRj1NdmYWl/CewpMFBJ8/f9pNfKMlaotMeVyavgRQQ5j37eRMZk9TDk10Pad2tBFPxQ1219y6DxEVY2YGuh5y6veBEQsxkePeGryA76Wodn8XFtd0xCTe8vK/i36Gm5zFasVIvWcKCoXRRlo="
    # TOGGL_PASSWORD
    - secure: "gCzIyfnAhqx6Ufv7A7C4flP9vmE6xmFOmOAzb94maYxwc6eMuxV0DCSUJNmjykBSss7l4e/dudUeKQF6evi2xw83S0OfeTEiuB3fJZr0rR+HIrmFdnhOCiph69bITzN9b90mUcYtfY0MSjBmAmAytM8/8HkRMmlhGqiMXNglMShq1nFx2PLSKwJrL4lwuVgDlR3kIhufZIT76SnFiFEEyJE0XfwcPbdvI4H5q0ERUIMN/hJ56TqK7bwO9cknKaBfZrhNYBX3OBJrGqRmM1bNZtmi9jvDCi72lNrIKqbXH/oUZjw5KjfA0GaCYuKeCvo9keOOyjTIF6vzHjtE/VXuvkAU1Y7uN22wDJ9CI/EA+9YHAca7VSPsafV/cRXZma7uOJLFSgY46nzSk3X+8AgfcDC9Iexs1BO8I4T85gEj3XZwm9H0ClEfDFo/HVWfDk68yVBaN9fNUuELpKVReSxaBPHNXTwaY9lj3J4NorQQ1fGEwN3d1M4u5yBDpu/xXtC88AIfsVuC0hw0tIk4CzVOseH0tdqywLRtvg3jMCzgTbaKHY1Dg6N7ske1HVihfM7hvoPSr1VQ0vPdU/3BBSA/0JqHzdm3p8FgbZlzLfoagYPAMuwO/No1/y/IsqqLk/i7ufNbvuQHD1AxzPq6BCFPiMQWOG86axPXSUR3tz4QcQg="
