os: linux
arch: amd64
dist: focal

language: ruby
rvm:
  - ruby-head
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1.10
  - 2.0.0-p648
script: bundle exec rspec --format documentation
cache: bundler
branches:
  only:
    - main
addons:
  code_climate:
    repo_token: eb44970f9efc497fb68c6ec1ce051dea530776b6a5bbe75e57734625f761ac86
env:
  global:
    - TOGGL_EMAIL=togglv8-limitusus@mailinator.com
    - TOGGL_USERNAME=Togglv8-Limitusus
    - TOGGL_USER_ID=6992251
    - OTHER_EMAIL=togglv8-limitusus2@mailinator.com
    - OTHER_USERNAME=Togglv8-Limitusus2
    - OTHER_USER_ID=6992583
    # COVERALLS_TOKEN
    - secure: "pypEjXOspyxJOk0g92omIUI58KH7UgFj4Sl27QjFIUcCRRmTezXR6srxJeVFtxJnFq1l/Jy0YOlE1RhMrPihqnclL1EYiO8NNquSvrkgA3P6lFvE0yIngYOxCY2G0SDRgPSnNNRZFndw7xw8rGAYbQU+M8FNTX70ekMLEBAVaX29nqh3eZhtYkwXGthJUsrTro1oZh640xZzwbWDUdjwdBUDe+gyG2qPy7xEKU97e/Ej1cFueBXK0dXsMLn2132zr0ahBVwUT10RNSuAUNxqq1jOT0yR2Nv5/N9ZfmUQF3jsjBHwRaQKm/rKpl8BQ6+V4xtC74cROtxecJvMLvjqibErkcaYtUlDi33m3WZ5zFv6XT3OIjzmAEo7W6wtI+/AcdOZlr8ysBAlRA0lZaqn57nkQK+NxI0k4uiyP6yCyoy5KNOgiIbqu0hYzQrMqZTXRxYiWbaWTB+krH9L2ZV0W7WFN4pRPzIML1WDij+lSYfoMBZADh25hEBhxmT9EhQjYezH6vfsFFyi+UEEz+ys9bwZIv9kWrbr7Vt76JIrJdK7jhLFSWigG+WaIro8qFvzcRCpxDtqFjFbEKZ6BYQu4FhT1aW0mC15oZR1ddci4ycP7PiC+dRBunyG+X7d/fQCHQTYke9ULScddxwQGAwrb8zimfU6kgFJDClGt/7+HiM="
    # TOGGL_API_TOKEN
    - secure: "eQa2PaA9023bwI0eujjobOCYmzru1Ik3Z6qlvAXhKG0Ql7OloN6PDCtPODTN7eciglSCE5RRG4xLiIuVv6yzgFN4oIZ+UTv/kZo3hRlYMLjBF3kxjRfsATRxM1dAD2AI6f+ZKR+tLWdw+lYQxDfM//qVCOU3yg4gGGEYyvctkUIHfTeTZzzW6KGoVj6I/xRQuDaQdpW5T3ueQme0a3uJRR5eRTGgJ7yI2y9QGgoc5DwgKGR7Cfl+eHd0CCh18jXZsnUA1c6TKJ1Y4LhG8oBABFPIEeOeoWlGttezTHvK0YtF+eaAuLvWWKA2WAWFCrgl/jWBXGdG8ixvTvig3VWngsR7IlZurvHqh6riU62G1mzjKEKDfiuK0sQ+bpJWN+SRap0zVPZ6YyMEhkLcu4rf3N+eHwvleFTx2z4Se6LE2ANJD/v5NbnR9E03M7DBqUKBx63SRgG950jBwBIMMnYrjvn68Ok6SstlSD5Qtmu2GBFZyPDPeCOJs0M5n5sx59Y6t0yitFrrwKthyBXbravWwuqVfj9YrDO4/h1f9UlZjURUZba0UFmfjNLXM43HaYUIyWrfYRHiygTpOcSLccB4ixmFYwbVwFI3z2BcSR3DwONDdLt9QzOZfhyJHV3Bb/rb6lSrqk6gSFG6oYyMgno0ED9pltMlmkGanDZCPKHhkpo="
    # TOGGL_PASSWORD
    - secure: "OU8VzzOI4kF/piuztxeqOFxAVtQ3GSxJDHN9IFHSDFTb6GuiuGTI+05Y89atQ2aOqfag2zVgwWRAuoZOA2yINq4C0Wf0kjNg8Z1l0DkuCCDtNPlnalC28j6wLP6OZQagtQqPVHT8Mwl5LvB+1NQNvBYNA4kcnHVa1AIPsquLVlkZiadae9r6Q7UatlhOeE4u4wRWBDWM73ZW1myPhoWNZCZAD6I8rYPKEPRzqTaYFj+t1oc1kdlPQDDcKq5Ep2ymNAEAHPueLnFFzjdFC/7LruadPRSLnQFkiP/1q/WF3FlDfDlJpqkXcr8bX9AU0R4OK0yZocU+GqlgX23yk9TVaDCTvdXnKkra0XH0oA8fewcCNYnUqmhYBewWu8c0kSzQG8Fue8vgQf99+kF0IV5dCcl+aL/5dAyEQlMeKhqEna6h+WfTFuufAqZvrOYbFXqQfmSkcm45AEzwYCaWqJI1prOatuWo3c2Of08T016bxRV9QcjQjit+84LtZ6XC9q7/b79S1a+0weS0X7z2usw3XuTTqlRSweKgNK5RXgQGt9Or4FhWxdoTYZQhkT7UqUq9d4A8tY2cBXwJQlzKepVJQ2QsWQd2zrr2m2QDBDKFKvkImkiW2Ij1VG5hoUKJ5l4XVpCGvDEMkqTyEq953b2UpjYaJUIMsHY1CQBR9SsRSIE="
